### ISSUE TITLE
[feature] add Github templates

### ISSUE THREAD

**Issue by Treggats** [mazedlx/laravel-feature-policy#19]
## Type of issue
improvement

## Background
I've done some code improvements in some, now merged, pull requests. However I think that the process to get to a pull request can be improved. 

By setting a standard on how issues/pull requests should be created, it will be easier to get a higher quality and a clearer picture of the issue/pull request.
Github offers templates for this, which can be included in the codebase. Which are used when an issue or pull request is created.

## Suggested change
add Github templates to the codebase to help with creating quality issues/pull requests.

**Comment by mazedlx** [comment]
I'll add you to this repo's collaborators.
