### ISSUE TITLE
[Feature]: set the test PR check as required

### ISSUE THREAD

**Issue by Treggats** [mazedlx/laravel-feature-policy#23]
### Type of request

improvement

### Requested change or question

Within Github Pull Requests it's possible to set certain workflows as required before a Pull Request can be merged.
I would suggest to enable this for the test workflow.

This prevents merging code that breaks the current codebase, which is in my opinion an improvement.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mazedlx** [comment]
If you could guide me to exactly where this setting can be changed, it'd be much appreciated ;-)
