### ISSUE TITLE
Update the available restrictable directives

### ISSUE THREAD

**Issue by mazedlx** [mazedlx/laravel-feature-policy#3]
Update the list of restrictable directives as mentioned in https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md

**Comment by Treggats** [comment]
I'll pick this up after I'm done with my PR for more QA on the codebase.

**Comment by Treggats** [comment]
@mazedlx there are a few existing constants which I can't find in the referenced in the specification.
What should we do with those?

The `XR`/`VR`/`XR_SPACIAL_TRACKING` especially are a bit weird.

```php
    public const VR = 'vr'; // after Chrome 79 replaced by xr-spatial-tracking
    public const WAKE_LOCK = 'wake-lock'; // looks like 'screen-wake-lock'
    public const XR = 'vr'; // perhaps an alias?
    public const SPEAKER = 'speaker'; /** @deprecated unknown directive */
    public const DOCUMENT_DOMAIN = 'document-domain'; /** @deprecated formerly in Chrome, behind a flag */
    public const XR_SPATIAL_TRACKING = 'xr-spatial-tracking'; // Implemented in Chrome as vr prior to Chrome 79.
```

The last two are present, but the former is deprecated and the last is kind of a replacement of some kind, based on the browsers version.

**Comment by Treggats** [comment]
> If they're not in the current spec, then they should be removed. TBH I didn't pay much attention to the spec since I've published the package 😅 Thanks for all the work!

Alright, what would this mean for versioning/releases? Just add a deprecate annotation and remove it in a later stage?
I'm also thinking in terms of the package versioning. Would you say that the work so far counts as a minor change? And that the work for this issue would count as a patch change?

**Comment by mazedlx** [comment]
> > If they're not in the current spec, then they should be removed. TBH I didn't pay much attention to the spec since I've published the package 😅 Thanks for all the work!
> 
> Alright, what would this mean for versioning/releases? Just add a deprecate annotation and remove it in a later stage? I'm also thinking in terms of the package versioning. Would you say that the work so far counts as a minor change? And that the work for this issue would count as a patch change?

Depracation notice in the next minor version.
Removal in the next major release.

**Comment by Treggats** [comment]
While working on this, the `Directive.php` got really big as I use anonymous classes.
I already moved these to a separate class. But it's still very big (>1000 lines).

Would you say it would better to use 'normal' classes, instead of one big class with all these classes?

See [this link](https://raw.githubusercontent.com/Treggats/laravel-feature-policy/feature/GH-3-expand-default-directives/src/FeatureGroups/DefaultFeatureGroup.php) on how the class now looks.

**Comment by mazedlx** [comment]
It has 1k lines but it isn't complex. Hard to say what would be better.

**Comment by Treggats** [comment]
> It has 1k lines but it isn't complex. Hard to say what would be better.

Exactly. The largest benefit that I see is that it's easy to reference within a docblock and thus getting faster to the definition.
And the mental load would be lower when everything is in separate classes. Easier to find to class you need.

These are DX (Developer eXperience) points, so the question would mostly be; what would help us most while maintaining this package.
