### ISSUE TITLE
[Bug]: Getting error Class App\Services\MyFeaturePolicy cannot extend final class Mazedlx\FeaturePolicy\Policies\Basic

### ISSUE THREAD

**Issue by ashwin-nath-m** [mazedlx/laravel-feature-policy#38]
### Contact Details

ashwin@springr.in

### What happened?

A bug happened!

### Version

2.0.0

### Relevant log output

```shell
fatal error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Treggats** [comment]
Hi Ashwin, thank you for reporting a bug.

Could you provide us with a bit more info regarding your issue?

My guess, from the title, is that you extend the `Basic` class to add your own directives.

The `Basic` class acts as an example. So you'll want to extend the `Policy` class, just like our `Basic` class does.

```diff
-class MyFeaturePolicy extends Mazedlx\FeaturePolicy\Policies\Basic
+class MyFeaturePolicy extends Mazedlx\FeaturePolicy\Policies\Policy
```

Let me know if you have any more questions.

**Comment by ashwin-nath-m** [comment]
Its fixed. I got it from the MyFeature Policy example in README which was extending Basic .
Thanks
