### ISSUE TITLE
[Bug]: Directive::XR_SPATIAL_TRACKING injects `vr` header value instead of `xr-spatial-tracking`

### ISSUE THREAD

**Issue by cemrich** [mazedlx/laravel-feature-policy#55]
### Contact Details

christine.coenen@3spin.com

### What happened?

I am running v2.1 and using the `Directive::XR_SPATIAL_TRACKING` directive, in a custom FeaturePolicy like so:

```php
<?php

namespace App\Http\FeaturePolicies;

use Mazedlx\FeaturePolicy\Directive;
use Mazedlx\FeaturePolicy\Policies\Policy;

class CustomFeaturePolicy extends Policy
{
    public function configure(): void
    {
        $this->addDirective(Directive::XR_SPATIAL_TRACKING, [
            'self',
            'https://sketchfab.com/',
        ]);
    }
}
```

This does inject the `Permissions-Policy` header just fine, uses the correct origin values, but uses the outdated `vr` key instead of `xr-spatial-tracking`:

![grafik](https://github.com/mazedlx/laravel-feature-policy/assets/403202/747c1985-57a2-4aaa-824c-2b108ebc604a)

Chrome 122 is not happy with this key:
![grafik](https://github.com/mazedlx/laravel-feature-policy/assets/403202/a3cdd7c6-e386-4796-b825-e0f5e514ccd5)

Given the fact, that there is a `Directive::VR` property for people to use, I would consider this behaviour a bug.

Thank you very much for this great package and please let me know, if you need more context!

(PS: The code of conduct leads to example.com)

### Version

2.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mazedlx** [comment]
@cemrich thank you for bringing this to our attention, the bug is fixed in the latest release.

**Comment by mazedlx** [comment]
We're happy to help!
