### ISSUE TITLE
[Bug]: placeholder values in report templates

### ISSUE THREAD

**Issue by Treggats** [mazedlx/laravel-feature-policy#56]
### What happened?

As reported by @cemrich in #55 

the template for reporting issues (bug/feature) have placeholder values in them.

### Version

2.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mazedlx** [comment]
I've updated the template for bug reports and removed the placeholders. @Treggats feel free to change them :-)
