### ISSUE TITLE
[Feature]: add "interest-cohort" feature policy

### ISSUE THREAD

**Issue by Treggats** [mazedlx/laravel-feature-policy#60]
### Type of request

improvement

### Requested change or question

I think it would be a good idea to, by default, disable the FLOC feature (Federated learning of cohorts)

This a build-in way for Google to track users using the Chrome browser.

https://www.howtogeek.com/724441/what-is-googles-floc-and-how-will-it-track-you-online/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mazedlx** [comment]
@Treggats I've updated the default directives set, but rector and phpstan fail with 8.2. Locally everything seems to be fine :-/

**Comment by Treggats** [comment]
@mazedlx I'll have a look this weekend to see what's going on.

**Comment by Treggats** [comment]
at a first glance it seems that either `pushMiddleware()` self is not present with PHP 8.2 or that it uses something only present in PHP 8.3 and up

**Comment by Treggats** [comment]
Got a fix kinda ready, want to do some more checking and find out why it stopped working to begin with.
